<?php

namespace AppBundle\Repository;

use AppBundle\Classes\PaginationHelper;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllByTitle($currentPage = 1, $limit = 5)
    {
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.title', 'ASC')
            ->getQuery();

        $paginator = PaginationHelper::paginate($query, $currentPage, $limit);

        return $paginator;
    }
}
