app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path: /
    defaults: { _controller: AppBundle:Home:index }

homepage_page:
    path: /{page}
    defaults: { _controller: AppBundle:Home:index }

single_author:
    path: /author/{id}/profile
    defaults: { _controller: AppBundle:Author:profile }

delete_author:
    path: /author/{id}/delete
    defaults: { _controller: AppBundle:Author:delete }

single_book:
    path: /book/{id}/profile
    defaults: { _controller: AppBundle:Book:profile }

delete_book:
    path: /book/{id}/delete
    defaults: { _controller: AppBundle:Book:delete }