app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path: /
    defaults: { _controller: AppBundle:Home:index }

homepage_page:
    path: /{page}
    defaults: { _controller: AppBundle:Home:index }

single_author:
    path: /author/{id}/profile
    defaults: { _controller: AppBundle:Author:profile }

edit_author:
    path: /author/{id}/edit
    defaults: { _controller: AppBundle:Author:edit }

delete_author:
    path: /author/{id}/delete
    defaults: { _controller: AppBundle:Author:delete }

add_author:
    path: /author/add
    defaults: { _controller: AppBundle:Author:add }

single_book:
    path: /book/{id}/profile
    defaults: { _controller: AppBundle:Book:profile }

edit_book:
    path: /book/{id}/edit
    defaults: { _controller: AppBundle:Book:edit }

delete_book:
    path: /book/{id}/delete
    defaults: { _controller: AppBundle:Book:delete }

add_book:
    path: /book/add
    defaults: { _controller: AppBundle:Book:add }