app:
    resource: '@AppBundle/Controller/'
    type: annotation

author_add:
    path:     /author/add/{name}
    defaults: { _controller: AppBundle:Author:add }

author_list:
    path:     /author/list
    defaults: { _controller: AppBundle:Author:list }

book_add_with_author:
    path:     /book/add
    defaults: { _controller: AppBundle:Book:create }