AppBundle\Entity\Book:
    type: entity
    table: book
    repositoryClass: AppBundle\Repository\BookRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        publishingYear:
            type: smallint
            column: publishing_year
        isbn:
            type: string
            length: '40'
            unique: true
        numberOfPages:
            type: smallint
            column: number_of_pages
    lifecycleCallbacks: {  }
